// 定义类型常量，默认全部大写
const TOKEN = 'TOKEN'
const USERINFO = 'USERINFO'
const LOGINSTATUS = 'LOGINSTATUS'
const CONCERN = 'CONCERN'
const CHANGE_CONCERN_NUMBER = 'CHANGE_CONCERN_NUMBER' //关注量
const CHANGE_GAME_NUMBER = 'CHANGE_GAME_NUMBER' //动态

const CHANGE_CHAT_LIST_TYPE = 'CHANGE_CHAT_LIST_TYPE' //改变聊天页面
const LOCATION = 'LOCATION' //位置信息

export default {
    TOKEN,
    USERINFO,
    LOGINSTATUS,
    CONCERN,
    CHANGE_CONCERN_NUMBER,
    CHANGE_GAME_NUMBER,
    CHANGE_CHAT_LIST_TYPE,
    LOCATION
}